# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JzN1sk0IsvUPLyxULRzqgKWDDc5ujfan
"""

import pandas as pd
import numpy as np

df = pd.read_excel('./Data TEST.xlsx')


country = df.drop(columns=['Theme'] , axis=1)

df1 = country.pivot_table(index=['Author', 'Sentiment'], columns=["Country"], aggfunc=np.count_nonzero).fillna(0).astype(bool)


theme = df.drop(columns=['Country'] , axis=1)


df2 = theme.pivot_table(index=['Author', 'Sentiment'], columns=["Theme"], aggfunc=np.count_nonzero).fillna(0).astype(bool)


answer = pd.concat([df1,df2] , 1, keys=['Country', 'Theme'])

writes = pd.ExcelWriter('test.xlsx')
answer.to_excel(writes,'answer')
writes.save()

